name: Python application test with Git'hub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3
      uses: actions/setup-python@v1
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: |
        make venv
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
